# This is an example YAML config file for templest
layout:
  _vars: # these variables are written to the top level of the directory, in "vars.tf"
    env: prod
    region: us-west-2
  vpc: # variables under here are written to templates in the vpc/ subdirectory
    _vars:
      sourcePath: "terraform-aws-modules/vpc/aws"
      name: my-vpc
      cidr: 10.0.0.0/16
      azs:
        - us-west-2a
        - us-west-2b
        - us-west-2c
      privateSubnets:
        - 10.0.1.0/24
        - 10.0.2.0/24
        - 10.0.3.0/24
      publicSubnets:
        - 10.0.101.0/24
        - 10.0.102.0/24
        - 10.0.103.0/24
    vpc_endpoints: # variables here are written to templates in the vpc_endpoints/ subdirectory of vpc/
      _vars:
        createDns: true
  lambda:
    _vars:
      sourcePath: "terraform-aws-modules/lambda/aws"
      runtime: "python3.8"
    src:
      _vars:
        bucket: "my-bucket-1234abcd"
        s3file: "myfile.txt"
